#!/bin/bash
set -e

# First-time server setup script for DigitalOcean VPS
# Run this once on a fresh Ubuntu 22.04+ droplet
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/YOUR_USER/yoga.tank.app/main/deploy/setup-server.sh | bash
#   OR
#   ssh root@your-server
#   bash setup-server.sh

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Image Generator - Server Setup Script          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: Please run as root${NC}"
    echo "sudo bash setup-server.sh"
    exit 1
fi

# Prompt for configuration
echo -e "${YELLOW}Configuration${NC}"
echo "─────────────────────────────────────────────────────"

read -p "Enter your domain name (e.g., app.example.com): " DOMAIN
read -p "Enter your GitHub repo URL (e.g., https://github.com/user/repo.git): " REPO_URL
read -p "Enter your Replicate API token: " REPLICATE_TOKEN
read -p "Enter admin password: " ADMIN_PASSWORD

# Generate JWT secret
JWT_SECRET=$(openssl rand -base64 32)

echo ""
echo -e "${GREEN}Installing dependencies...${NC}"

# Update system
apt-get update && apt-get upgrade -y

# Install Docker
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Installing Docker...${NC}"
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    echo -e "${GREEN}Docker already installed${NC}"
fi

# Install Docker Compose plugin
if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}Installing Docker Compose...${NC}"
    apt-get install -y docker-compose-plugin
fi

# Install git
apt-get install -y git curl

# Configure firewall
echo -e "${GREEN}Configuring firewall...${NC}"
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# Clone repository
APP_DIR="/opt/yoga-tank"
echo -e "${GREEN}Cloning repository to ${APP_DIR}...${NC}"

if [ -d "$APP_DIR" ]; then
    echo -e "${YELLOW}Directory exists, pulling latest...${NC}"
    cd "$APP_DIR"
    git pull origin main
else
    git clone "$REPO_URL" "$APP_DIR"
    cd "$APP_DIR"
fi

# Create .env.production
echo -e "${GREEN}Creating .env.production...${NC}"
cat > .env.production << EOF
# Production environment configuration
# Generated by setup-server.sh on $(date)

# Required
REPLICATE_API_TOKEN=${REPLICATE_TOKEN}
JWT_SECRET=${JWT_SECRET}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Server
NODE_ENV=production
PORT=3001
DOMAIN=${DOMAIN}

# Encryption key for API keys (auto-generated)
ENCRYPTION_KEY=$(openssl rand -hex 32)

# Optional S3 storage (configure later if needed)
# S3_ENDPOINT=
# S3_BUCKET=
# S3_ACCESS_KEY=
# S3_SECRET_KEY=
EOF

chmod 600 .env.production

# Create data directories
mkdir -p data generated-images uploads

# Build and start
echo -e "${GREEN}Building and starting services...${NC}"
docker compose -f docker-compose.prod.yml build
docker compose -f docker-compose.prod.yml up -d

# Wait for health check
echo -e "${YELLOW}Waiting for services to start...${NC}"
sleep 10

# Check status
docker compose -f docker-compose.prod.yml ps

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Setup Complete!                       ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "1. Point your domain DNS A record to this server's IP"
echo "2. Wait for DNS propagation (can take up to 48 hours)"
echo "3. Access your app at https://${DOMAIN}"
echo ""
echo -e "${BLUE}Useful commands:${NC}"
echo "  cd ${APP_DIR}"
echo "  docker compose -f docker-compose.prod.yml logs -f    # View logs"
echo "  docker compose -f docker-compose.prod.yml restart    # Restart"
echo "  docker compose -f docker-compose.prod.yml down       # Stop"
echo ""
echo -e "${BLUE}For GitHub Actions auto-deploy, add these secrets:${NC}"
echo "  VPS_HOST: $(curl -s ifconfig.me)"
echo "  VPS_USER: root"
echo "  VPS_SSH_KEY: (your SSH private key)"
echo ""
echo -e "${YELLOW}Important: Save your JWT_SECRET somewhere safe!${NC}"
echo "JWT_SECRET: ${JWT_SECRET}"
